def Addition():
    X = int(input("Input X :"))
    Y = int(input("Input Y :"))
    print(X, "+", Y, "=", X+Y)

Addition()
Addition()
Addition()
Addition()
Addition()
Addition()
Addition()
Addition()
Addition()
Addition()
